import type { NextPage } from "next";
import Head from "next/head";
import { GasPrice } from "../components/gasPrice";

const Page: NextPage = () => {
  return (
    <div>
      <Head>
        <title>GasChecker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <GasPrice />
      </main>

      <footer></footer>
    </div>
  );
};

export default Page;
